const mongoose=require("mongoose")

const userSchema = new mongoose.Schema({
    image: { type: String, required: true },
    district: { type: String, required: true },
    thana: { type: String, required: true },
    flatno: { type: String, required: true },
    house_no: { type: String, required: true },
    road_no: { type: String, required: true },
    alaka: { type: String, required: true },
    postcode: { type: String, required: true },
    fname: { type:String, required:true },
    Father_name: { type: String, required: true },
    date_of_birth: { type: Date, required: true },
    married_status: { type: String, required: true },
    Present_address: { type: String, required: true },
    Office_address: { type: String, required: true },
    religion: { type: String, required: true },
    edu_Qualification: { type: String, required: true },
    mobile_number: { type: String, required: true },
    email: { type: String, required: true, unique: true },
    nid_number:{ type:String, required:true, unique:true },
    p_number: { type: String, required: true },
    E_name: { type: String, required: true },
    relation: { type: String, required: true },
    e_address: { type: String, required: true },
    e_number: { type: String, required: true },
    name: { type: String, required: true },
    age: { type: Number, required: true },
    occupation: { type: String, required: true },
    mobile_number: { type: String, required: true },
    name1: { type: String },
    age1: { type: Number },
    occupation1: { type: String },
    mobile_number1: { type: String },
    name2: { type: String },
    age2: { type: Number },
    occupation2: { type: String },
    mobile_number2: { type: String },
    house_wife: { type: String, required: true },
    housewife_nid_number: { type: String, required: true },
    housewife_mobile_number: { type: String, required: true },
    housewife_Present_address: { type: String, required: true },
    driver_name: { type: String, required: true },
    driver_nid_number: { type: String, required: true },
    driver_mobile_number: { type: String, required: true },
    driver_Present_address: { type: String, required: true },
    previous_houseowner_name: { type: String, required: true },
    previous_houseowner_mobile_number: { type: String, required: true },
    previous_houseowner_address: { type: String, required: true },
    reason_toleave_previous_house: { type: String, required: true },
    present_houseowner_name: { type: String, required: true },
    present_houseowner_mobile_number: { type: String, required: true },
    timeof_startLiving_in_newhouse: { type: Date, required: true },
    form_fill_date: { type: Date, required: true },
    sign_image: { type: String, required: true },
})

const UserDetail=new mongoose.model("UserDetail",userSchema)

module.exports=UserDetail